version: "3.6"


services:
  api:
    build: .
    restart: always
    environment:
      DB_DSN: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      OPENAPI_PREFIX: '/api'
    networks:
      frontend:
        aliases:
          - space_dyakov_to
      backend:
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend


networks:
  frontend:
    name: web
    external: true
  backend:

volumes:
  postgres:
    name: shopping_list-data
