version: "3.6"


services:
  api:
    build: .
    restart: always
    env_file: .env
    networks:
      frontend:
        aliases:
          - space_dyakov_to
      backend:
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend


networks:
  frontend:
    name: web
    external: true
  backend:

volumes:
  postgres:
    name: redirect-data
